### ISSUE TITLE
Building C++ unit tests on OSX Yosemite fails due to Zookeeper bug

### ISSUE THREAD

**Issue by papayawarrior** [dato-code/Dato-Core#13]
Initially reported on the Dato forum:

http://forum.dato.com/discussion/883/error-running-c-units

Relevant error output:

```
[ 26%] Performing build step for 'zookeeper'
libtool: compile: /usr/bin/clang -DHAVE_CONFIG_H -I. -I./include -I./tests -I./generated -fPIC -Wall -Werror -fPIC -MT zookeeper.lo -MD -MP -MF .deps/zookeeper.Tpo -c src/zookeeper.c -o zookeeper.o
In file included from src/zookeeper.c:27:
In file included from ./include/zookeeper.h:34:
./include/recordio.h:76:9: error: expected ')'
```
Looks like a Zookeeper bug was filed and fixed last October, so I think it's just a question of updating the Zookeeper version.

https://issues.apache.org/jira/browse/ZOOKEEPER-2049

**Comment by jasonchaw** [comment]
Hi!

A fix to this issue was kindly merged by Jay Gu earlier today. 
See https://github.com/dato-code/Dato-Core/commit/b661132578b5a54550a71b88ffa6e32cddffddc4

Cheers!

**Comment by TobyRoseman** [comment]
Thanks Jason.

**Comment by jasonchaw** [comment]
You are welcome! :)
